log_dir: ./log/model/
data:
  data_file: ./data/SonTay.csv
  split_point_outer: 0.05
  split_point_inner: 0.4
  norm_method: min_max
  cols_x:
    - 3
    - 2
  cols_y:
    - 3
    - 2
  cols_gt:
    - 3
    - 2
  window_size: 30
  target_timestep: 1
model:
  epoch_min: 100
  epoch_max: 250
  epoch_step: 50
  epochs_out: 400
  in_dim: 2
  out_dim: 2
  patience: 100
  batch_size: 128
  dropout: 0